export const SET_FAVOURITES = "SET_FAVOURITES";

export const SET_RECIPIES = "SET_RECIPIES";
export const SET_RECIPE = "SET_RECIPE";
export const SET_RECIPIES_LOADING = "SET_RECIPIES_LOADING";
export const SET_RECIPE_LOADING = "SET_RECIPE_LOADING";