export const SET_FAVOURITES = "SET_FAVOURITES";
export const SET_FAVOURITESLOADING = "SET_FAVOURITESLOADING";
export const SET_POPULAR = "SET_POPULAR"
export const SET_POPULARLOADING = "SET_POPULARLOADING"

export const SET_RECIPIES = "SET_RECIPIES";
export const SET_RECIPE = "SET_RECIPE";
export const SET_RECIPIES_LOADING = "SET_RECIPIES_LOADING";
export const SET_RECIPE_LOADING = "SET_RECIPE_LOADING";

